# Generated by Django 4.2.16 on 2024-12-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
