# Generated by Django 5.1.6 on 2025-02-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0003_category_subscribers_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='User',
            new_name='user',
        ),
    ]
